[versions]
kotlin = "2.3.10"

# Testing
kotest = "6.1.3"

# Logging
logback = "1.5.28"
kotlinLogging = "8.0.01"
slf4j = "2.0.17"

[plugins]
kotest = { id = "io.kotest", version.ref = "kotest" }

[libraries]
# Logging
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlinLogging" }

# Testing
kotest-framework = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
